import json
import numpy as np
import os


def get_videoartgs_params(model_dir):
    """
    Load the joint metadata and predicted joint states generated by VideoArtGS.

    Args:
        model_dir: Directory containing joint_info.json and joint_value.npy.

    Returns:
        active_joints: Metadata for all detected active joints.
        final_state: Predicted joint-state changes from the initial frame
                     to the final frame.
    """

    # 1. Load the static joint parameters from joint_info.json
    json_path = os.path.join(model_dir, "joint_info.json")

    with open(json_path, "r") as file:
        joint_infos = json.load(file)

    # Keep only the active joints according to the current filtering rule
    active_joints = [
        joint
        for joint in joint_infos
        if joint.get("joint", "fixed") != "heavy"
    ]

    # 2. Load the dynamic joint parameters from joint_value.npy
    npy_path = os.path.join(model_dir, "joint_value.npy")
    raw_states = np.load(npy_path)

    # Compute the joint-state change from the initial frame
    # to the final frame
    final_state = (
        raw_states[-1].squeeze()
        - raw_states[0].squeeze()
    )

    return active_joints, final_state


# Run the parameter extraction
model_dir = (
    "../outputs/videoartgs/sapien/168/"
    "final/train/ours_20000/"
)

joints, state = get_videoartgs_params(model_dir)

print(f"Number of detected active joints: {len(joints)}")

for i, joint in enumerate(joints):
    axis = joint.get("jointData", {}).get("axis")
    position = joint.get("center")

    if np.ndim(state) > 0:
        predicted_state = state[i]
    else:
        predicted_state = state

    print(f"Joint {i} axis: {axis}")
    print(f"Joint {i} position: {position}")
    print(f"Joint {i} final predicted state: {predicted_state}")